{
 "title": "Explorer Backend Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Current Connections",
   "type": "gauge",
   "description": "Database Current Connections",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hikaricp_connections" }
   ]
  },
  {
   "title": "DB Active Connections",
   "type": "gauge",
   "description": "Database Active Connections",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "hikaricp_active_connections" }
   ]
  },
  {
   "title": "DB Idle Connections",
   "type": "gauge",
   "description": "Database Idle Connections",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "hikaricp_idle_connections" }
   ]
  },
  {
   "title": "DB Pending Threads",
   "type": "gauge",
   "description": "Threads Awaiting Connection",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "hikaricp_pending_threads" }
   ]
  },
  {
   "title": "Number of Requests Per Second",
   "type": "graph",
   "description": "Number of requests per second, grouped by endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(explorer_backend_request_total{app=\"explorer-backend\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(irate(explorer_backend_request_total{app=\"explorer-backend\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Failed Requests Count",
   "type": "graph",
   "description": "Failed requests count in last 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(explorer_backend_request_total{app=\"explorer-backend\",status=\"5xx\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(explorer_backend_request_duration_seconds_bucket{app=\"explorer-backend\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(explorer_backend_request_duration_seconds_bucket{app=\"explorer-backend\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(explorer_backend_request_duration_seconds_bucket{app=\"explorer-backend\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(irate(explorer_backend_request_duration_seconds_sum{app=\"explorer-backend\"}[1m])) / sum(irate(explorer_backend_request_duration_seconds_count{app=\"explorer-backend\"}[1m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average Request Duration By Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(explorer_backend_request_duration_seconds_sum{app=\"explorer-backend\"}[1m])) by (path)) / (sum(irate(explorer_backend_request_duration_seconds_count{app=\"explorer-backend\"}[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Postgres Transactions Per Second",
   "type": "graph",
   "description": "Postgres transactions per second(committed + rollback)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(postgres_transactions_total{app=\"explorer-backend\"}[1m])",
     "legendFormat": "Transactions Per Second"
    }
   ]
  },
  {
   "title": "Postgres Disk Blocks Read Per Second",
   "type": "graph",
   "description": "Postgres disk blocks read per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(postgres_blocks_hits_total{app=\"explorer-backend\"}[1m])",
     "legendFormat": "Blocks Read From Cache"
    },
    {
     "expr": "irate(postgres_blocks_reads_total{app=\"explorer-backend\"}[1m])",
     "legendFormat": "Blocks Read From Disk"
    }
   ]
  },
  {
   "title": "Postgres Rows Read/Write Per Second",
   "type": "graph",
   "description": "Postgres rows read/write per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(postgres_rows_fetched_total{app=\"explorer-backend\"}[1m])",
     "legendFormat": "Rows Fetched"
    },
    {
     "expr": "irate(postgres_rows_inserted_total{app=\"explorer-backend\"}[1m])",
     "legendFormat": "Rows Inserted"
    },
    {
     "expr": "irate(postgres_rows_updated_total{app=\"explorer-backend\"}[1m])",
     "legendFormat": "Rows Updated"
    },
    {
     "expr": "irate(postgres_rows_deleted_total{app=\"explorer-backend\"}[1m])",
     "legendFormat": "Rows Deleted"
    }
   ]
  }
 ]
}